suppressMessages(library(energy))
suppressMessages(library(dplyr))
suppressMessages(library(SeuratObject))
suppressMessages(library(SingleCellExperiment))
suppressMessages(library(remotes))
suppressMessages(library(devtools))
suppressMessages(library(Biobase))
suppressMessages(library(Seurat))
suppressMessages(library(future.apply))
suppressMessages(library(DWLS))
suppressMessages(library(data.table))

# === Parameter parsing update: accept input and output arguments from the Bash script ===
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2) {
  stop("Error: both the input RDS path and the output directory path must be provided！", call. = FALSE)
}
input_rds <- args[1]   # Corresponds to $DEFAULT_REF_RDS in the Bash script (Sing cell reference)
output_dir <- args[2]  # Corresponds to $DEFAULT_OUTPUT_DIR in the Bash script
# ========================================================

# Replace the hard-coded input and output paths in the original code:
sc <- readRDS(input_rds)

##prepare single cell reference
# sc <- readRDS(list1[[i]])
Idents(sc) <- "CellType"
celltype <- unique(sc$CellType)
if ("Unknown cells" %in% celltype == TRUE) {
  sc <- subset(sc, idents = "Unknown cells", invert = TRUE)   
}
counts <- data.frame(sc@assays$RNA@counts)
meta <- data.frame(sc@meta.data)
phenoData <- data.frame(cbind(meta$CellType, meta$sample))
rownames(phenoData) <- rownames(meta)
names(phenoData) <- c("CellType","sample")

# === Path update: store the temporary MAST signature matrix in the shared output directory ===
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
Signature <- buildSignatureMatrixMAST(scdata = counts, id = phenoData[,"CellType"], path = output_dir, diff.cutoff = 0.5, pval.cutoff = 0.01)
# ====================================================================

##input bulk data (tpm)
# === Path update: dynamically read the pseudo-bulk data generated by module 2.1 from the Uniform_Fraction directory pseudo.txt ===
pseudo_tpm_path <- file.path(output_dir, "Uniform_Fraction", "random_pseudo", "pseudo.txt")
tpm <- fread(pseudo_tpm_path)
# ====================================================================================
tpm <- na.omit(tpm)

##run DWLS
res <- data.frame()
for (j in 1:ncol(tpm)) {
  b = setNames(tpm[,j], rownames(tpm))
  tr <- trimData(Signature, b)
  RES <- data.frame(t(solveDampenedWLS(tr$sig, tr$tpm)))
  res <- rbind(res,RES)
}
rownames(res) <- colnames(tpm)
res[res < 10^-5] <- 0

# === Path update: dynamically create the result subdirectory using output_dir passed from the Bash script and save the predicted proportions ===
dwls_out_dir <- file.path(output_dir, "Results_DWLS", "Results")
dir.create(dwls_out_dir, recursive = TRUE, showWarnings = FALSE)
write.csv(res, file.path(dwls_out_dir, "Predict_DWLS.csv"))
# ===============================================================================
